name: Generate mihomo 

on:
  schedule:
    - cron: "30 22 * * *" # 6:30 AM UTC+8
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  generate_lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Pull Changes
        run: git pull

      - name: Set up Node.js (if required)
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust if needed

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl wget git jq
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)
         
      - name: Download and install Mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64-alpha.*.deb" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O mihomo-linux-amd64-alpha.deb
          sudo apt install --fix-missing ./mihomo-linux-amd64-alpha.deb
        shell: bash
        
      - name: Generate ru-bundle
        env:
          NO_SKIP: true
        run: |
         mkdir ru-bundle
         wget -O /ru-bundle/temp.lst https://github.com/legiz-ru/sb-rule-sets/raw/main/ru-bundle.lst
         echo "payload:" > /ru-bundle/rule.yaml && cat /ru-bundle/temp.lst | sed "s/.*/- '+.&'/" >> /ru-bundle/rule.yaml
         mihomo convert-ruleset domain yaml /ru-bundle/rule.yaml /ru-bundle/rule.mrs
         
      - name: Delete temp file
        run: |
          rm /ru-bundle/temp.lst | rm mihomo-linux-amd64-alpha.deb
          
      - name: Get current date
        id: date
        run: |
          echo "DATE=$(TZ=Europe/Moscow date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: githubaction@githubaction.com
          message: 'Generating .srs rule-sets ${{ env.DATE }}'
          push: true
          cwd: .
          default_author: github_actor
          fetch: --tags --force
          pathspec_error_handling: ignore
          github_token: ${{ secrets.RULESET_TOKEN }}
