name: Generate mihomo 

on:
  schedule:
    - cron: "30 1 * * *" 
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  generate_lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Pull Changes
        run: git pull

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl wget git jq
         
      - name: Download and install Mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64-alpha.*.deb" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O mihomo-linux-amd64-alpha.deb
          sudo apt install --fix-missing ./mihomo-linux-amd64-alpha.deb
        shell: bash
        
      - name: Generate ru-bundle
        env:
          NO_SKIP: true
        run: |
         mkdir -p ru-bundle
         wget -O ru-bundle.lst https://github.com/legiz-ru/sb-rule-sets/raw/main/ru-bundle.lst
         wget -O itdoginfo-inside-russia.lst https://github.com/itdoginfo/allow-domains/raw/main/Russia/inside-raw.lst
         wget -O antifilter-community.lst https://community.antifilter.download/list/domains.lst
         wget -O no-russia-hosts.json https://github.com/legiz-ru/sb-rule-sets/raw/main/no-russia-hosts.json
         jq -r '.rules[].domain_suffix[]' no-russia-hosts.json > no-russia-hosts.lst
         echo "payload:" > rule.yaml && cat ru-bundle.lst | sed "s/.*/- '+.&'/" >> rule.yaml
         mihomo convert-ruleset domain yaml rule.yaml rule.mrs
         sed 's/^/+\./' ru-bundle.lst > rule.list
         echo "payload:" > itdoginfo-inside-russia.yaml && cat itdoginfo-inside-russia.lst | sed "s/.*/- '+.&'/" >> itdoginfo-inside-russia.yaml
         mihomo convert-ruleset domain yaml itdoginfo-inside-russia.yaml itdoginfo-inside-russia.mrs
         echo "payload:" > antifilter-community.yaml && cat antifilter-community.lst | sed "s/.*/- '+.&'/" >> antifilter-community.yaml
         mihomo convert-ruleset domain yaml antifilter-community.yaml antifilter-community.mrs
         echo "payload:" > no-russia-hosts.yaml && cat no-russia-hosts.lst | sed "s/.*/- '+.&'/" >> no-russia-hosts.yaml
         mihomo convert-ruleset domain yaml no-russia-hosts.yaml no-russia-hosts.mrs
         mv rule.yaml rule.mrs rule.list itdoginfo-inside-russia.yaml itdoginfo-inside-russia.mrs antifilter-community.yaml antifilter-community.mrs no-russia-hosts.yaml no-russia-hosts.mrs ru-bundle/

      - name: Generate re-filter
        env:
          NO_SKIP: true
        run: |
         mkdir -p re-filter
         wget -O re-filter-ip.text https://github.com/1andrevich/Re-filter-lists/raw/main/ipsum.lst
         mihomo convert-ruleset ipcidr text re-filter-ip.text ip-rule.mrs
         wget -O re-filter-domain.text https://github.com/1andrevich/Re-filter-lists/raw/main/domains_all.lst
         mihomo convert-ruleset domain text re-filter-domain.text domain-rule.mrs
         mv domain-rule.mrs ip-rule.mrs re-filter/

      - name: Generate oisd
        env:
          NO_SKIP: true
        run: |
         mkdir -p oisd
         wget -O oisd_big.txt https://github.com/sjhgvr/oisd/raw/main/domainswild2_big.txt
         wget -O oisd_nsfw.txt https://github.com/sjhgvr/oisd/raw/main/domainswild2_nsfw.txt
         wget -O oisd_nsfw_small.txt https://github.com/sjhgvr/oisd/raw/main/domainswild2_nsfw_small.txt
         wget -O oisd_small.txt https://github.com/sjhgvr/oisd/raw/main/domainswild2_small.txt
         mihomo convert-ruleset domain text oisd_big.txt big.mrs
         mihomo convert-ruleset domain text oisd_nsfw.txt nsfw.mrs
         mihomo convert-ruleset domain text oisd_nsfw_small.txt nsfw_small.mrs
         mihomo convert-ruleset domain text oisd_small.txt small.mrs
         mv big.mrs nsfw.mrs nsfw_small.mrs small.mrs oisd/

      - name: Generate other rulesets
        env:
          NO_SKIP: true
        run: |
         mkdir -p other
         wget -O torrent-websites.txt https://github.com/sakib-m/Pi-hole-Torrent-Blocklist/raw/main/all-torrent-websites.txt
         wget -O torrent-trackers.txt https://github.com/sakib-m/Pi-hole-Torrent-Blocklist/raw/main/all-torrent-trackres.txt
         wget -O torrent-clients.json https://github.com/legiz-ru/sb-rule-sets/raw/main/torrent-clients.json
         mihomo convert-ruleset domain text torrent-websites.txt torrent-websites.mrs
         mihomo convert-ruleset domain text torrent-trackers.txt torrent-trackers.mrs
         echo "payload:" > torrent-clients.yaml && jq -r '.rules[] | .rules[] | .process_name[], .package_name[]' torrent-clients.json | awk '{print "  - PROCESS-NAME," $0}' >> torrent-clients.yaml
         mv torrent-websites.mrs torrent-trackers.mrs torrent-clients.yaml other/

      - name: Generate v2ray templates for vpnbot
        env:
          NO_SKIP: true
        run: |
         mkdir -p other
         wget -O other/vpnbot-v2ray-ru-bundle.json https://github.com/mercurykd/vpnbot/raw/dev/config/v2ray.json
         domains=$(cat ru-bundle.lst | jq -R . | jq -s .) && jq --argjson domains "$domains" '(.routing.rules | to_entries | .[] | select(.value.outboundTag == "block").key + 1) as $idx | .routing.rules = .routing.rules[0:$idx] + [{"type": "field", "outboundTag": "~outbound~", "domain": $domains}] + .routing.rules[$idx:]' other/vpnbot-v2ray-ru-bundle.json > temp.json && mv temp.json other/vpnbot-v2ray-ru-bundle.json
         domains=$(grep -vE '^#|^$' oisd_small.txt | jq -R . | jq -s .) && jq --argjson domains "$domains" '(.routing.rules | to_entries | .[] | select(.value.outboundTag == "block").key + 1) as $idx | .routing.rules = .routing.rules[0:$idx] + [{"type": "field", "outboundTag": "block", "domain": $domains}] + .routing.rules[$idx:]' other/vpnbot-v2ray-ru-bundle.json > other/vpnbot-v2ray-ru-bundle-oisd-small.json
         
      - name: Delete temp file
        run: |
          rm ru-bundle.lst | rm re-filter-ip.text | rm re-filter-domain.text | rm mihomo-linux-amd64-alpha.deb
          rm itdoginfo-inside-russia.lst | rm antifilter-community.lst | rm no-russia-hosts.json | rm no-russia-hosts.lst
          rm oisd_big.txt | rm oisd_nsfw.txt | rm oisd_nsfw_small.txt | rm oisd_small.txt
          rm torrent-websites.txt | rm torrent-trackers.txt | rm torrent-clients.json
          
      - name: Get current date
        id: date
        run: |
          echo "DATE=$(TZ=Europe/Moscow date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: githubaction@githubaction.com
          message: 'Generating .mrs rule-sets ${{ env.DATE }}'
          push: true
          cwd: .
          default_author: github_actor
          fetch: --tags --force
          pathspec_error_handling: ignore
          github_token: ${{ secrets.RULESET_TOKEN }}
